CREATE TABLE ADirectory(
	ADUserId INT PRIMARY KEY NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Pwd VARCHAR(100) NOT NULL,
	ADId VARCHAR(100) NOT NULL,
	FirtsName VARCHAR(100) NOT NULL,
	LastName VARCHAR(100) NOT NULL,
	UserName VARCHAR(100) NOT NULL,
	Position VARCHAR(100) NOT NULL,
	Area VARCHAR(100) NOT NULL
)

CREATE TABLE RefreshTokens(
	RefreshTokenId INT PRIMARY KEY NOT NULL,
	UserID VARCHAR(100) NOT NULL,
	DateIssued DATETIME NOT NULL,
	DateExpired DATETIME NOT NULL,
	IsUsed BIT NOT NULL,
	IsActive BIT NOT NULL,
	TokenValue NVARCHAR(MAX) NOT NULL
)

CREATE TABLE Users(
	UserId INT PRIMARY KEY NOT NULL,
	UserADId VARCHAR(100) NOT NULL
)

CREATE TABLE Roles(
	RolId INT PRIMARY KEY NOT NULL,
	RolName VARCHAR(50) NOT NULL,
	Codigo VARCHAR(100) NOT NULL,
	Estado BIT NOT NULL
)

CREATE TABLE Funcionality(
	FuncionalityId INT PRIMARY KEY NOT NULL,
	CodTramite VARCHAR(100) NOT NULL,
	NameFunc VARCHAR(100) NOT NULL,
	Codigo VARCHAR(100) NOT NULL,
	Estado BIT NOT NULL
)

CREATE TABLE User_Rol(
	User_RolId INT PRIMARY KEY NOT NULL,
	UserId INT NOT NULL,
	RolId INT NOT NULL,
	FuncionalityId INT NOT NULL
)

ALTER TABLE User_Rol ADD CONSTRAINT FK_User_Rol_Funcionality FOREIGN KEY (FuncionalityId) REFERENCES Funcionality (FuncionalityId)
ALTER TABLE User_Rol ADD CONSTRAINT FK_User_Rol_Roles FOREIGN KEY (RolId) REFERENCES Roles (RolId)
ALTER TABLE User_Rol ADD CONSTRAINT FK_User_Rol_Users FOREIGN KEY (UserId) REFERENCES Users (UserId)

CREATE TABLE Funcionality_Rol(
	Funcionality_RolId VARCHAR(100) PRIMARY KEY NOT NULL,
	FuncionalityId INT NOT NULL,
	RolId INT NOT NULL,
	Estado BIT NOT NULL
)

ALTER TABLE Funcionality_Rol ADD CONSTRAINT FK_Funcionality_Rol_Funcionality FOREIGN KEY (FuncionalityId) REFERENCES Funcionality (FuncionalityId)
ALTER TABLE Funcionality_Rol ADD CONSTRAINT FK_Funcionality_Rol_Roles FOREIGN KEY (RolId) REFERENCES Roles (RolId)